---
- block:
  - name: ensure Docker CE (Debian)
    ansible.builtin.apt:
      name: docker.io
    when: ansible_facts.os_family == "Debian"

  - name: ensure {{ ansible_user }} is assigned to docker group
    ansible.builtin.user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes

  - name: ensure enabled & started Docker daemon
    ansible.builtin.service:
      name: docker
      enabled: yes
      state: started

  become: true
