---
- hosts: jetson
  tags: spark_setup

  tasks:
    - name: check if Scala directory exists
      ansible.builtin.stat:
        path: "/usr/local/{{ scala_name }}"
      register: scala_dir

    - name: download Scala tarball
      ansible.builtin.get_url:
        url: "{{ scala_tarball }}"
        dest: /tmp/scala.tgz
      when: not scala_dir.stat.exists

    - name: install Scala tarball
      ansible.builtin.unarchive:
        src: /tmp/scala.tgz
        dest: /usr/local
        owner: "{{ ansible_user }}"
        remote_src: true
      when: not scala_dir.stat.exists
      become: true

    - name: link Scala folder
      ansible.builtin.file:
        src: "/usr/local/{{ scala_name }}"
        dest: /usr/local/scala
        owner: "{{ ansible_user }}"
        group: root
        state: link
      become: true

    - name: check if Spark directory exists
      ansible.builtin.stat:
        path: "/usr/local/{{ spark_name }}"
      register: spark_dir

    - name: download Spark tarball
      ansible.builtin.get_url:
        url: "{{ spark_tarball }}"
        dest: /tmp/spark.tgz
      when: not spark_dir.stat.exists

    - name: install Spark tarball
      ansible.builtin.unarchive:
        src: /tmp/spark.tgz
        dest: /usr/local
        owner: "{{ ansible_user }}"
        remote_src: true
      when: not spark_dir.stat.exists
      become: true

    - name: link Spark folder
      ansible.builtin.file:
        src: "/usr/local/{{ spark_name }}"
        dest: /usr/local/spark
        owner: "{{ ansible_user }}"
        group: root
        state: link
      become: true

    - name: include paths in global environment
      ansible.builtin.copy:
        dest: /etc/environment
        src: "etc/environment"
        mode: "0644"
      become: true

    - name: upload configuration for all nodes
      ansible.builtin.template:
        dest: "/usr/local/spark/conf/{{ item }}"
        src: "etc/{{ item }}"
      with_items:
        - "spark-env.sh"

    - name: upload worker configuration
      ansible.builtin.template:
        dest: /usr/local/spark/conf/slaves
        src: "etc/slaves"
