---
- hosts: jetson

  pre_tasks:
    - name: ensure up-to-date packages
      ansible.builtin.import_tasks: includes/updated/tasks.yaml

  roles:
    - role: roles/common-tools
    - role: roles/security-config
    - role: roles/docker-host

  tasks:
    - name: disable graphical login manager
      ansible.builtin.service:
        name: gdm
        enabled: false
      become: true
